### ISSUE TITLE
I was wondering if you might bring this up to 1.12?

### ISSUE THREAD

**Issue by RapidfireCRH** [bence98/Librarian#1]
I know its been 3 years but any chance you might upgrade it so we can use it to store these ungodly number of mod books i have?

Thanks

**Comment by bence98** [comment]
I sure can, but this week is going to be a busy one for me, so it'll probably take a few days before I can get round to it.
In fact, it should probably build on 1.12 with small modfications, if you want to try. The mod is under CC0, which means you are allowed to build it from source, modified or not, and even publish it as your own. Though if you sent in a pull request, that'd be nice.

TL;DR: yes, but it's going to take time. If you want, you can do it on your own, which should not be hard. If not, then I'll eventually (when I'm done with the IRL stuff) update it and send you a ping.

**Comment by bence98** [comment]
@RapidfireCRH So, I'm done with IRL stuff (soooo done...). I updated the mod to 1.12.2, enjoy! If there's any bugs in it, please open a new issue instead of posting to this one.
Edit: You can find and download the new version from CurseForge.
